[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "metric_ui"
version = "0.1.0"
description = "AI Observability Metric Summarizer"

dependencies = [
    "requests",
    "llama-stack-client",
]

[project.optional-dependencies]
test = [
    "pytest",
]